# author: Francois Doray <francois.pierre-doray@polymtl.ca>


import os.path


Import('root_env')

cppunit = SConscript(os.path.join('cppunit', 'SConscript'),
                     exports=['root_env'])

Return(['cppunit'])
